exports.province = [
    {name: "Bangkok"},
    { name: "Phuket" },
    { name: "Chiang Mai" },
    { name: "Krabi" },
    { name: "Ayutthaya" },
    { name: "Pattaya" },
    { name: "Samut Prakan" },
    { name: "Hua Hin" },
    { name: "Nakhon Ratchasima" },
    { name: "Chonburi" },
    { name: "Songkhla" },
    { name: "Udon Thani" },
    { name: "Surat Thani" },
    { name: "Kanchanaburi" },
    { name: "Nakhon Sawan" },
    { name: "Rayong" },
    { name: "Khon Kaen" },
    { name: "Nonthaburi" },
    { name: "Lampang" },
    { name: "Ratchaburi" },
    { name: "Nakhon Pathom" },
    { name: "Sukhothai" },
    { name: "Samut Songkhram" },
    { name: "Suphan Buri" },
    { name: "Loei" },
    { name: "Saraburi" },
    { name: "Chanthaburi" },
    { name: "Trang" },
    { name: "Phra Nakhon Si Ayutthaya" },
    { name: "Maha Sarakham" },
    { name: "Nakhon Si Thammarat" },
    { name: "Petchburi" },
    { name: "Chaiyaphum" },
    { name: "Sa Kaeo" },
    { name: "Kamphaeng Phet" },
    { name: "Phang Nga" },
    { name: "Narathiwat" },
    { name: "Kalasin" },
    { name: "Prachin Buri" },
    { name: "Satun" },
    { name: "Uttaradit" },
    { name: "Nong Bua Lamphu" },
    { name: "Lop Buri" },
    { name: "Sisaket" },
    { name: "Yasothon" },
    { name: "Prachuap Khiri Khan" },
    { name: "Chachoengsao" },
    { name: "Buriram" },
    { name: "Ranong" },
    { name: "Phatthalung" },
    { name: "Nakhon Nayok" },
    { name: "Phetchabun" },
    { name: "Nakhon Phanom" },
    { name: "Roi Et" },
    { name: "Surin" },
    { name: "Yala" },
    { name: "Mukdahan" },
    { name: "Chumphon" },
    { name: "Nong Khai" },
    { name: "Amnat Charoen" },
    { name: "Si Sa Ket" },
    { name: "Phichit" },
    { name: "Phetchaburi" },
    { name: "Samut Sakhon" },
    { name: "Ubon Ratchathani" },
    { name: "Ang Thong" },
    { name: "Pathum Thani" },
    { name: "Nakhon Sawan" },
    { name: "Sukhothai" },
    { name: "Phayao" },
    { name: "Mae Hong Son" },
    { name: "Lamphun" },
    { name: "Nan" },
    { name: "Bueng Kan" },
    { name: "Tak" },
    { name: "Sing Buri" },
    { name: "Trat" },
  ];
  

