module.exports = events = [
    {
        organizerInformationId: 1,
        coverImage: "https://th.bing.com/th/id/OIP.UXGikObFpH0-hFMv4PqQ5AHaE8?rs=1&pid=ImgDetMain",
        title: "Watarun",
        description: "the best wat in thailand",
        startDate: new Date("2024-10-03"),
        endDate: new Date("2024-12-03"),
        categoryId: 1,
        timePeriod: "08:00-17:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://i0.wp.com/www.planitscotland.com/wp-content/uploads/2019/02/Screenshot-2019-01-13-18.29.24.png?resize=1061%2C675&ssl=1",
        title: "Adventure Fest",
        description: "Explore the wonders of nature",
        startDate: new Date("2024-08-10"),
        endDate: new Date("2024-12-10"),
        categoryId: 2,
        timePeriod: "09:00-18:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://th.bing.com/th/id/OIP.L0qZk0VrcReuvsTnC86dvQHaEf?rs=1&pid=ImgDetMain",
        title: "Culinary Delight",
        description: "A feast for food lovers",
        startDate: new Date("2024-07-12"),
        endDate: new Date("2024-11-12"),
        categoryId: 3,
        timePeriod: "11:00-20:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://th.bing.com/th/id/OIP.HX9vI8f_ltVpZZ8QFQD_UgHaDQ?rs=1&pid=ImgDetMain",
        title: "Tech Expo",
        description: "Innovations that shape the future",
        startDate: new Date("2024-09-08"),
        endDate: new Date("2024-05-08"),
        categoryId: 4,
        timePeriod: "10:00-17:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://th.bing.com/th/id/OIP.Bhs6ZRSadFaVZ0X_57fsIgHaEK?w=960&h=540&rs=1&pid=ImgDetMain",
        title: "Fusion Beats",
        description: "A musical journey across genres",
        startDate: new Date("2024-11-15"),
        endDate: new Date("2024-12-15"),
        categoryId: 4,
        timePeriod: "06:00-22:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage:
            "https://th.bing.com/th/id/R.2f1c0dcd0efdc9a971aad02b7bda9694?rik=Z%2fpaPm9%2bRyMonA&riu=http%3a%2f%2fwww.youauthorus.com%2fwp-content%2fuploads%2f2016%2f04%2fArtistic-Vibes-Room-Cover-picture-2.jpg&ehk=MkvK%2f3yroG7YlV903fxUSFzUpOOrsupX9AyexM5jT48%3d&risl=&pid=ImgRaw&r=0",
        title: "Artistic Vibes",
        description: "Celebrating creativity in all forms",
        startDate: new Date("2024-06-09"),
        endDate: new Date("2024-10-09"),
        categoryId: 4,
        timePeriod: "09:30-18:30",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 1,
        coverImage: "https://i.pinimg.com/originals/f2/63/9d/f2639dee1d6460e14174a1a8d1b0c906.jpg",
        title: "Mindful Retreat",
        description: "Embrace tranquility and peace",
        startDate: new Date("2024-04-11"),
        endDate: new Date("2024-06-11"),
        categoryId: 2,
        timePeriod: "10:00-18:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://4.bp.blogspot.com/-EMvD6vUHTIA/VgFIN8ROxBI/AAAAAAAAOos/3CA4UOnhiiw/s1600/Diner%2Bgrand%2Bchefs.png",
        title: "Gastronomy Gala",
        description: "A culinary journey around the world",
        startDate: new Date("2024-12-14"),
        endDate: new Date("2024-12-30"),
        categoryId: 2,
        timePeriod: "12:00-21:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://th.bing.com/th/id/OIP.gLIdv4Atvq0TKvmeoDKKcAHaE7?rs=1&pid=ImgDetMain",
        title: "Code Confluence",
        description: "Where coding brilliance meets",
        startDate: new Date("2024-03-13"),
        endDate: new Date("2024-05-13"),
        categoryId: 2,
        timePeriod: "01:30- 21:30",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://th.bing.com/th/id/OIP.z_HjQ5K5e_LVRLDKO_1jXQHaE8?rs=1&pid=ImgDetMain",
        title: "Fashion Fiesta",
        description: "A showcase of style and trends",
        startDate: new Date("2024-02-16"),
        endDate: new Date("2024-03-16"),
        categoryId: 3,
        timePeriod: "04:00-23:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://th.bing.com/th/id/OIP.DjOD3ruErmdzcQ33rwMDZQHaE8?rs=1&pid=ImgDetMain",
        title: "Health Harmony",
        description: "Wellness for mind and body",
        startDate: new Date("2024-05-10"),
        endDate: new Date("2024-10-10"),
        categoryId: 4,
        timePeriod: "09:00-17:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage: "https://www.fodors.com/wp-content/uploads/2019/02/shutterstock_1086090431.jpg",
        title: "Cultural Carnival",
        description: "Diverse traditions under one roof",
        startDate: new Date("2024-07-12"),
        endDate: new Date("2024-09-12"),
        categoryId: 5,
        timePeriod: "11:30-20:30",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://th.bing.com/th/id/OIP.na7waxfAEiF8AQSI2Q-HogHaEg?rs=1&pid=ImgDetMain",
        title: "Tech Summit",
        description: "Exploring the future of technology",
        startDate: new Date("2024-09-08"),
        endDate: new Date("2024-12-08"),
        categoryId: 6,
        timePeriod: "10:00-18:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    //========================================= real mock ================================================//
    {
        organizerInformationId: 6,
        coverImage: "https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg",
        title: "Pattaya Firework Festival",
        description:
            "The Pattaya International Fireworks Festival is an annual event held in Pattaya, Thailand, which is known for its beautiful beaches and vibrant nightlife. The festival typically takes place over two days and features fireworks displays from various countries around the world.During the festival, visitors can enjoy spectacular pyrotechnic shows set against the backdrop of Pattaya's stunning coastline. The fireworks are launched from barges anchored offshore, creating a dazzling display of colors and shapes that light up the night sky.",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-15"),
        categoryId: 5,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 1,
        coverImage: "https://s359.kapook.com//pagebuilder/dd957864-6f4f-47b7-aae5-8def120c9e3c.jpg",
        title: "Khao Wang Firework Festival",
        description:
            "The Khao Wang Firework Festival refers to an annual event held in Phetchaburi, Thailand, at Khao Wang, also known as Phra Nakhon Khiri Historical Park. Phra Nakhon Khiri is a historical palace complex atop a hill, offering scenic views of the surrounding area. The festival typically takes place during the annual long weekend in December, celebrating the birthday of King Rama IV, who had a residence at the palace.",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-16"),
        categoryId: 6,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://images.pexels.com/photos/625789/pexels-photo-625789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        title: "Yee Peng Lanna",
        description:
            "The Yee Peng Lanna Festival in Northern Thailand is a magical event where thousands of floating lanterns illuminate the night sky, symbolizing good fortune and releasing worries. This cultural celebration, held during the full moon of the twelfth lunar month, features traditional music, dance, and delectable cuisine, offering a rich cultural experience in the heart of Chiang Mai",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-10"),
        categoryId: 1,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 3,
        coverImage: "https://dimg04.c-ctrip.com/images/0M70o120009hc3h5f8BC4_Q60.jpg_.webp",
        title: "Big Mountain music festival",
        description:
            "The Big Mountain Music Festival is one of the largest and most popular music festivals in Thailand. It typically takes place annually in December and is held at Bonanza Khao Yai, a scenic outdoor venue located near Khao Yai National Park.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-11"),
        categoryId: 4,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "http://chiangraiballoonfiesta.com/assets/base/img/content/gallery/feb2018/28.jpg",
        title: "Singha Park Ballon Festival",
        description:
            "A Balloon Festival typically refers to an event where hot air balloons are prominently featured. These festivals are popular attractions in many places around the world, often drawing large crowds of spectators and participants.During a balloon festival, visitors can usually expect to see a variety of hot air balloons of different shapes, sizes, and colors. There may be opportunities for rides in the balloons (sometimes for a fee), as well as tethered balloon rides where the balloon is anchored to the ground and goes up and down but does not fly freely.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-13"),
        categoryId: 2,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 5,
        coverImage:
            "https://assets.editorial.aetnd.com/uploads/2010/02/lunarnewyearfestival.jpg?width=1920&height=960&crop=1920%3A960%2Csmart&quality=75&auto=webp",
        title: "Chinese New Year",
        description:
            "Chinese New Year, also known as the Spring Festival, is the most important traditional festival in Chinese culture. It marks the beginning of the lunar new year and is celebrated by Chinese communities around the world. The date of Chinese New Year varies each year according to the lunar calendar, typically falling between January 21st and February 20th on the Gregorian calendar.The festival is celebrated with various customs, traditions, and activities, which may vary among different regions and communities. Some common elements of Chinese New Year celebrations include",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-17"),
        categoryId: 2,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://upload.wikimedia.org/wikipedia/en/5/5c/Ghosts.PeeTaKhon2.jpg",
        title: "Phi Ta Khon",
        description:
            "Phi Ta Khon (Thai: ผีตาโขน; phǐi taa khǒn; [pʰǐː taː kʰǒn]) is a festival held in Dan Sai, Loei province, Isan, Thailand. The events take place over three days sometime between March and July, the dates being selected annually by the town’s mediums.The whole event is called Bun Luang, part of a Buddhist merit-making holiday also known as Bun Phawet (assembly day). The town’s residents invite protection from Phra U-pakut, the spirit of the Mun river. They then hold a series of games and take part in a procession wearing masks made of the sheaths or bottom part of thick palm leaf stems.",
        startDate: new Date("2024-03-13"),
        endDate: new Date("2024-03-14"),
        categoryId: 2,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://mpics.mgronline.com/pics/Images/566000009624503.JPEG",
        title: "Phuket Vegeterian Festival",
        description:
            "The Phuket Vegetarian Festival is an annual event held in Phuket, Thailand. It usually takes place during the ninth lunar month of the Chinese calendar. The festival is celebrated by the Chinese community in Phuket, who observe a strict vegetarian diet for nine days as a form of purification and merit-making.During the festival, participants dress in white and refrain from consuming meat, poultry, seafood, and other animal products. They also avoid certain strong-smelling vegetables such as garlic and onions. Many devotees perform acts of self-mortification, including piercing their cheeks with various objects and participating in processions to honor the Nine Emperor Gods.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-13"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage: "https://s.isanook.com/ho/0/ud/3/15073/b-3.jpg",
        title: "Boon Bang Fai",
        description:
            "Boon Bang Fai, also known as the Rocket Festival, is an annual traditional festival celebrated in northeastern Thailand, particularly in the region of Isan. The festival usually takes place around May, marking the beginning of the rainy season and aiming to encourage rainfall for successful agricultural harvests.During the Boon Bang Fai festival, communities build large bamboo rockets, often decorated elaborately, and launch them into the sky. The rockets are believed to provoke the rain gods to bring much-needed rainfall to the region. The festival is accompanied by lively music, dancing, and parades, creating a festive atmosphere.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-11"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://cdn.i-scmp.com/sites/default/files/d8/images/canvas/2023/04/03/8cb12ab6-e927-4b3f-b754-cac99e33d64f_c6f7589c.jpg",
        title: "Songkran Festival",
        description:
            "The Songkran Festival is one of the most important and widely celebrated traditional festivals in Thailand. It marks the Thai New Year and usually falls on April 13th every year, although the celebration may extend for several days, depending on the region.The festival is known for its water-related activities, where people engage in friendly water fights and douse each other with water as a symbol of cleansing and purification for the new year. Water is also used to wash away bad luck and to bring good fortune for the upcoming year. During Songkran, streets across Thailand are transformed into lively water battlegrounds, with locals and tourists alike armed with water guns, hoses, and buckets.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-12"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 4,
        coverImage: "https://cms.dmpcdn.com/travel/2020/09/28/3dae42c0-0164-11eb-97e4-65e826b4aa8c_original.JPG",
        title: "Naga Fireball",
        description:
            "The fireballs are most often reported around the night of Wan Ok Phansa at the end of Buddhist Lent in late-October.[3] Naga fireballs have been reported over an approximately 250 km (160 mi) long section of the Mekong River centered approximately on Phon Phisai in the Phon Phisai District. Fireballs have also been reported rising from smaller rivers, lakes and ponds in the region. The fireballs were called 'ghost lights' by locals until the mid-1980s, when the local council officially named them phaya nak lights. In 2018 one observer noted that while the light phenomenon is 'hundreds of years old', the new name Phaya Nak lights is only about 35 years old.",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-16"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://cms.dmpcdn.com/travel/2021/07/20/601500a0-e940-11eb-812d-d3adbb9acce8_original.jpg",
        title: "Buddism Candle Festival",
        description:
            "The term Buddhism Candle Festival could refer to various festivals or events related to Buddhism that involve candles. One example is the Vesak Day or Buddha Day,which is celebrated by Buddhists around the world to commemorate the birth, enlightenment, and death of Gautama Buddha. During Vesak Day, candles are often lit as part of the celebrations to symbolize enlightenment and to honor the Buddha's teachings",
        startDate: new Date("2024-03-17"),
        endDate: new Date("2024-03-18"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://www.theakyra.com/files/5015/7043/7475/Bo_Sang_Umbrella_Festival.jpg",
        title: "Full moon PhaNgarn island",
        description:
            "Koh Phangan Full Moon Party has become a world-famous institution, but its ancestral home remains the crescent cove of Haad Rin Beach on the southernmost tip of Phangan Island in Thailand. More than 12 powerful sound systems turn the 800-metre beach into possibly the most popular open-air nightclub in the world once a month, with a lively festival-like atmosphere, great music and huge quantities of alcohol. This one-of-a-kind event is routinely listed on bucket lists as one of the essential experiences in Thailand which absolutely must be seen to be believed.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-13"),
        categoryId: 4,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 1,
        coverImage: "https://a.cdn-hotels.com/gdcs/production31/d653/09d20665-cfa3-4efd-a423-9b30dc2517d2.jpg?impolicy=fcrop&w=1600&h=1066&q=medium",
        title: "Bo Sang Umbrella Festival",
        description:
            "The Bo Sang Umbrella Festival is an annual event held in Bo Sang Village near Chiang Mai, Thailand. Celebrated for over a century, it showcases the traditional craft of umbrella making with vibrant displays of hand-painted umbrellas and parasols. Visitors can witness colorful parades, cultural performances, and participate in umbrella painting workshops. This festival highlights the rich cultural heritage of the region and attracts tourists from around the world.",
        startDate: new Date("2025-01-19"),
        endDate: new Date("2025-01-19"),
        categoryId: 4,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage: "https://f.ptcdn.info/530/032/000/1434550481-DSC032601j-o.jpg",
        title: "Ayuthaya Light up",
        description:
            "Ayutthaya: the former capital of Siam, Ayutthaya had palaces laden with gold, large monuments and elaborate Buddha's - all of this grandeur came to an end when the Burmese burnt the city to the ground, destroying all of its riches. Now all that remains are ruins of the historic events that took place there - the city is now on the list of UNESCO world heritage sites. Take a trip to this incomparable ancient city with local Bangkok tours, where you will get the best prices along with the best experiences",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-16"),
        categoryId: 6,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 3,
        coverImage: "https://i0.wp.com/www.tatnews.org/wp-content/uploads/2022/07/Sukhothai-Historical-Park-1.jpg?fit=1200%2C742&ssl=1",
        title: "Sukhothai Light up",
        description:
            "Sukhothai: the former capital of Siam, Ayutthaya had palaces laden with gold, large monuments and elaborate Buddha's - all of this grandeur came to an end when the Burmese burnt the city to the ground, destroying all of its riches. Now all that remains are ruins of the historic events that took place there - the city is now on the list of UNESCO world heritage sites. Take a trip to this incomparable ancient city with local Bangkok tours, where you will get the best prices along with the best experiences",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-17"),
        categoryId: 6,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://pbs.twimg.com/media/GHM43aqaoAASopM?format=jpg&name=900x900",
        title: "Khao Wong Prajan Light up",
        description:
            "Khao Wong Prajarn is a Thai term that translates to Moon Crescent Hill in English. This is a famous historical site located in Ratchaburi Province, Thailand. It is also known as Khao Phra Chan or Khao Chan Daeng.Khao Wong Prajarn is renowned for its unique natural rock formations, which resemble a crescent moon when viewed from a distance. These formations are believed to have been naturally shaped over millions of years by erosion and weathering processes.",
        startDate: new Date("2024-03-18"),
        endDate: new Date("2024-03-19"),
        categoryId: 2,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 5,
        coverImage: "https://media.komchadluek.net/media/img/size1/2017/06/30/zogb5hih55kideefeaabki7a.jpg?x-image-process=style/LG-webp",
        title: "Buffalo racing",
        description:
            "The Buffalo Racing Festival or Wing Kwai is one of the most exciting events of the calendar in Chonburi province. The annual race is held in celebration of the water buffalo as an icon of Thailand’s agrarian way of life, giving locals a chance to get together, compete in thrilling competitions, and enjoy delicious, local cuisine.Dating back to 150 years ago, the event is perfect for anyone looking for a unique Thai experience that cannot be found elsewhere.",
        startDate: new Date("2024-03-14"),
        endDate: new Date("2024-03-17"),
        categoryId: 3,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://s.isanook.com/tr/0/ud/278/1391125/2.jpg",
        title: "Long Boat racing",
        description:
            "The season of long boat races is finally here. Long boat-racing has always been one of Thailand’s signature sport festivals, held annually during Thai Buddhist Lent period which is around September and October since the river’s tide is highest. The purpose is to display the bond between local Thais and the river and to show moral, courage, and strength of the rowing crew. It has been being held since the old Thai era (approx. 600 year ago.)",
        startDate: new Date("2024-03-18"),
        endDate: new Date("2024-03-20"),
        categoryId: 3,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage:
            "https://scontent.fbkk7-3.fna.fbcdn.net/v/t31.18172-8/18238565_1683026615048444_7055562275172768252_o.jpg?_nc_cat=108&ccb=1-7&_nc_sid=5f2048&_nc_ohc=mYgcPbmMyhoAX_qBHLv&_nc_oc=AQk47M-mASY1KGX_UNOfQSEe6-77Z_501_uh2Ku9PSp9Yd729PJhr0BtljqY7KkSi-Y&_nc_ht=scontent.fbkk7-3.fna&oh=00_AfCwUIdF1hRDheKCE6cleedvySo9m1dEGDObkAKjNbWNPg&oe=660FBADA",
        title: "Water Thai Boxing",
        description:
            "When it comes to sports in Thailand, the first thing that comes to mind is Muay Thai. But do you know about the origins of Thailand’s National Sport? Team Thailand Insider is here to share with you the history, important Muay Thai figures, and where to watch the jaw-clenching sport in Thailand.As Thailand’s national sport, Muay Thai, or Thai Boxing, is the most popular sport in the country. As a martial art originating from the Siamese army, people travel from all over the globe to learn this historically rooted sport. Muay Thai is referred to as “The Art of Eight Limbs” due to the eight points of contact the body uses, mimicking weapons of war.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-15"),
        categoryId: 3,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage:
            "https://ryuisnow.com/wp-content/uploads/2023/03/%E0%B8%9E%E0%B8%B8%E0%B9%88%E0%B8%87%E0%B9%83%E0%B8%95%E0%B9%89%E0%B9%80%E0%B8%9F%E0%B8%AA-4-1024x683.jpg",
        title: "Chang Music Connection",
        description:
            "The Chang Music Festival is a popular music festival held in Thailand. It is organized by Chang Beer, a well-known Thai beer brand. The festival typically features a diverse lineup of local and international artists across various music genres, including pop, rock, electronic dance music (EDM), hip-hop, and more.The Chang Music Festival is known for its vibrant atmosphere, with attendees enjoying live music performances, food and drinks, and other entertainment activities. The festival often attracts large crowds and has become a significant event in Thailand's music scene.",
        startDate: new Date("2024-03-08"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 3,
        coverImage: "https://image.springnews.co.th/uploads/images/md/2024/02/ZUU5By9qNOMpIjZg4bXC.webp?x-image-process=style/LG-webp",
        title: "Pattaya Music Pattaya",
        description:
            "The Pattaya Music Festival is an annual event held in the beach city of Pattaya, Thailand. It typically takes place over a weekend and features a wide range of musical performances across various genres, including pop, rock, jazz, electronic dance music (EDM), and traditional Thai music.The festival attracts both local and international artists, showcasing talent from Thailand and beyond. It often spans multiple stages set up along the beach, allowing attendees to enjoy different acts while taking in the scenic views of the coastline.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "19:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://mpics.mgronline.com/pics/Images/557000003809501.JPEG",
        title: "Tractor racing",
        description:
            "Tractor racing is a unique motorsport where modified tractors compete against each other in races. These races typically take place on dirt tracks or fields, and the tractors are specially designed and modified for racing purposes.In tractor racing, competitors often modify their tractors to enhance performance, including upgrading the engine, improving traction, and optimizing weight distribution. Some modifications may also involve adding safety features such as roll cages and seat belts to protect the drivers.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 5,
        coverImage:
            "https://d12eu00glpdtk2.cloudfront.net/public/images/news/visit-qatar-kite-festival-returns-second-edition-25-january-2024/_910x600_clip_center-center_none/visit-qatar-kite-festival-returns-second-edition-25-january-2024-cover-image.jpeg",
        title: "Cha-Am Kite Festival",
        description:
            "The Cha-Am International Kite Festival is a vibrant annual event held in Cha-Am, a beach resort town in Thailand. The festival typically takes place in March and attracts kite enthusiasts from around the world.During the Cha-Am Kite Festival, the skies above the beach are filled with colorful kites of various shapes and sizes. Participants showcase their creativity and skills by flying kites of traditional designs as well as more elaborate and innovative creations",
        startDate: new Date("2024-03-14"),
        endDate: new Date("2024-03-15"),
        categoryId: 5,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://images.ahotu.com/9zsf3d2n86q3ldrn4x6rua4g0mpq?w=1920&f=webp",
        title: "Huahin Marathon",
        description:
            "The Hua Hin Marathon is an annual running event held in Hua Hin, Thailand. Hua Hin is a popular beach resort town located on the Gulf of Thailand, known for its beautiful beaches and vibrant atmosphere. The marathon typically takes place in either late spring or early winter, depending on the specific year.The Hua Hin Marathon offers various race distances to cater to runners of different levels and preferences. These may include a full marathon (42.195 kilometers), a half marathon (21.1 kilometers), a 10-kilometer race, and sometimes shorter distances for children or fun runs.",
        startDate: new Date("2024-03-20"),
        endDate: new Date("2024-03-22"),
        categoryId: 3,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 1,
        coverImage: "https://images.ahotu.com/6brr1pa3mw5wu4sjzjbajj9l62mk?w=1920&f=webp",
        title: "Bangsaen Marathon",
        description:
            "Come join us for the prestigious BANGSAEN42 CHONBURI MARATHON! Ranked number one for two consecutive years as the Best Full Marathon Event (by WingNaiDee) and winner of the Runners’ Choice 2018 Award, this full marathon race consists of 42.195 km and is the only MICE & Communication Marathon of the year.",
        startDate: new Date("2024-03-19"),
        endDate: new Date("2024-03-20"),
        categoryId: 3,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage: "https://images.ahotu.com/31wp709d97v6gyja2lkikf9mvafy?w=1920&f=webp",
        title: "Amazing Thailand Marathon",
        description:
            "Experience the renowned hospitality of Thailand and join world-class athletes on an incredible running route in Bangkok. Run through must-see sights such as the Victory Monument, King Rama V Monument, and Rama VIII Bridge, beginning at the Rajamangala National Stadium and ending at the Democracy Monument. With four categories to choose from – Marathon, Half Marathon, 10km, and 5km Family Fun Run – there's something for everyone, no matter your running experience. Come join us and have some fun!",
        startDate: new Date("2024-03-22"),
        endDate: new Date("2024-03-24"),
        categoryId: 3,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
]
