module.exports = events = [
    {
        organizerInformationId: 1,
        coverImage: "https://th.bing.com/th/id/OIP.UXGikObFpH0-hFMv4PqQ5AHaE8?rs=1&pid=ImgDetMain",
        title: "Watarun",
        description: "the best wat in thailand",
        startDate: new Date("2024-10-03"),
        endDate: new Date("2024-12-03"),
        categoryId: 1,
        timePeriod: "08:00-17:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://i0.wp.com/www.planitscotland.com/wp-content/uploads/2019/02/Screenshot-2019-01-13-18.29.24.png?resize=1061%2C675&ssl=1",
        title: "Adventure Fest",
        description: "Explore the wonders of nature",
        startDate: new Date("2024-08-10"),
        endDate: new Date("2024-12-10"),
        categoryId: 2,
        timePeriod: "09:00-18:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://th.bing.com/th/id/OIP.L0qZk0VrcReuvsTnC86dvQHaEf?rs=1&pid=ImgDetMain",
        title: "Culinary Delight",
        description: "A feast for food lovers",
        startDate: new Date("2024-07-12"),
        endDate: new Date("2024-11-12"),
        categoryId: 3,
        timePeriod: "11:00-20:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://th.bing.com/th/id/OIP.HX9vI8f_ltVpZZ8QFQD_UgHaDQ?rs=1&pid=ImgDetMain",
        title: "Tech Expo",
        description: "Innovations that shape the future",
        startDate: new Date("2024-09-08"),
        endDate: new Date("2024-05-08"),
        categoryId: 4,
        timePeriod: "10:00-17:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://th.bing.com/th/id/OIP.Bhs6ZRSadFaVZ0X_57fsIgHaEK?w=960&h=540&rs=1&pid=ImgDetMain",
        title: "Fusion Beats",
        description: "A musical journey across genres",
        startDate: new Date("2024-11-15"),
        endDate: new Date("2024-12-15"),
        categoryId: 4,
        timePeriod: "06:00-22:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage:
            "https://th.bing.com/th/id/R.2f1c0dcd0efdc9a971aad02b7bda9694?rik=Z%2fpaPm9%2bRyMonA&riu=http%3a%2f%2fwww.youauthorus.com%2fwp-content%2fuploads%2f2016%2f04%2fArtistic-Vibes-Room-Cover-picture-2.jpg&ehk=MkvK%2f3yroG7YlV903fxUSFzUpOOrsupX9AyexM5jT48%3d&risl=&pid=ImgRaw&r=0",
        title: "Artistic Vibes",
        description: "Celebrating creativity in all forms",
        startDate: new Date("2024-06-09"),
        endDate: new Date("2024-10-09"),
        categoryId: 4,
        timePeriod: "09:30-18:30",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 1,
        coverImage: "https://i.pinimg.com/originals/f2/63/9d/f2639dee1d6460e14174a1a8d1b0c906.jpg",
        title: "Mindful Retreat",
        description: "Embrace tranquility and peace",
        startDate: new Date("2024-04-11"),
        endDate: new Date("2024-06-11"),
        categoryId: 2,
        timePeriod: "10:00-18:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://4.bp.blogspot.com/-EMvD6vUHTIA/VgFIN8ROxBI/AAAAAAAAOos/3CA4UOnhiiw/s1600/Diner%2Bgrand%2Bchefs.png",
        title: "Gastronomy Gala",
        description: "A culinary journey around the world",
        startDate: new Date("2024-12-14"),
        endDate: new Date("2024-12-30"),
        categoryId: 2,
        timePeriod: "12:00-21:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://th.bing.com/th/id/OIP.gLIdv4Atvq0TKvmeoDKKcAHaE7?rs=1&pid=ImgDetMain",
        title: "Code Confluence",
        description: "Where coding brilliance meets",
        startDate: new Date("2024-03-13"),
        endDate: new Date("2024-05-13"),
        categoryId: 2,
        timePeriod: "01:30- 21:30",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://th.bing.com/th/id/OIP.z_HjQ5K5e_LVRLDKO_1jXQHaE8?rs=1&pid=ImgDetMain",
        title: "Fashion Fiesta",
        description: "A showcase of style and trends",
        startDate: new Date("2024-02-16"),
        endDate: new Date("2024-03-16"),
        categoryId: 3,
        timePeriod: "04:00-23:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://th.bing.com/th/id/OIP.DjOD3ruErmdzcQ33rwMDZQHaE8?rs=1&pid=ImgDetMain",
        title: "Health Harmony",
        description: "Wellness for mind and body",
        startDate: new Date("2024-05-10"),
        endDate: new Date("2024-10-10"),
        categoryId: 4,
        timePeriod: "09:00-17:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage: "https://www.fodors.com/wp-content/uploads/2019/02/shutterstock_1086090431.jpg",
        title: "Cultural Carnival",
        description: "Diverse traditions under one roof",
        startDate: new Date("2024-07-12"),
        endDate: new Date("2024-09-12"),
        categoryId: 5,
        timePeriod: "11:30-20:30",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://th.bing.com/th/id/OIP.na7waxfAEiF8AQSI2Q-HogHaEg?rs=1&pid=ImgDetMain",
        title: "Tech Summit",
        description: "Exploring the future of technology",
        startDate: new Date("2024-09-08"),
        endDate: new Date("2024-12-08"),
        categoryId: 6,
        timePeriod: "10:00-18:00",
        isYearly: false,
        isPublish: true,
        isExpired: false,
    },
    //========================================= real mock ================================================//
    {
        organizerInformationId: 6,
        coverImage: "https://images.pexels.com/photos/2526105/pexels-photo-2526105.jpeg",
        title: "Pattaya Firework Festival",
        description:
            "The Pattaya International Fireworks Festival is an annual event held in Pattaya, Thailand, which is known for its beautiful beaches and vibrant nightlife. The festival typically takes place over two days and features fireworks displays from various countries around the world.During the festival, visitors can enjoy spectacular pyrotechnic shows set against the backdrop of Pattaya's stunning coastline. The fireworks are launched from barges anchored offshore, creating a dazzling display of colors and shapes that light up the night sky.",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-15"),
        categoryId: 5,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 1,
        coverImage: "https://s359.kapook.com//pagebuilder/dd957864-6f4f-47b7-aae5-8def120c9e3c.jpg",
        title: "Khao Wang Firework Festival",
        description:
            "The Khao Wang Firework Festival refers to an annual event held in Phetchaburi, Thailand, at Khao Wang, also known as Phra Nakhon Khiri Historical Park. Phra Nakhon Khiri is a historical palace complex atop a hill, offering scenic views of the surrounding area. The festival typically takes place during the annual long weekend in December, celebrating the birthday of King Rama IV, who had a residence at the palace.",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-16"),
        categoryId: 6,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://images.pexels.com/photos/625789/pexels-photo-625789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        title: "Yee Peng Lanna",
        description:
            "The Yee Peng Lanna Festival in Northern Thailand is a magical event where thousands of floating lanterns illuminate the night sky, symbolizing good fortune and releasing worries. This cultural celebration, held during the full moon of the twelfth lunar month, features traditional music, dance, and delectable cuisine, offering a rich cultural experience in the heart of Chiang Mai",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-10"),
        categoryId: 1,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 3,
        coverImage: "https://dimg04.c-ctrip.com/images/0M70o120009hc3h5f8BC4_Q60.jpg_.webp",
        title: "Big Mountain music festival",
        description:
            "The Big Mountain Music Festival is one of the largest and most popular music festivals in Thailand. It typically takes place annually in December and is held at Bonanza Khao Yai, a scenic outdoor venue located near Khao Yai National Park.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-11"),
        categoryId: 4,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "http://chiangraiballoonfiesta.com/assets/base/img/content/gallery/feb2018/28.jpg",
        title: "Singha Park Ballon Festival",
        description:
            "A Balloon Festival typically refers to an event where hot air balloons are prominently featured. These festivals are popular attractions in many places around the world, often drawing large crowds of spectators and participants.During a balloon festival, visitors can usually expect to see a variety of hot air balloons of different shapes, sizes, and colors. There may be opportunities for rides in the balloons (sometimes for a fee), as well as tethered balloon rides where the balloon is anchored to the ground and goes up and down but does not fly freely.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-13"),
        categoryId: 2,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 5,
        coverImage:
            "https://assets.editorial.aetnd.com/uploads/2010/02/lunarnewyearfestival.jpg?width=1920&height=960&crop=1920%3A960%2Csmart&quality=75&auto=webp",
        title: "Chinese New Year",
        description:
            "Chinese New Year, also known as the Spring Festival, is the most important traditional festival in Chinese culture. It marks the beginning of the lunar new year and is celebrated by Chinese communities around the world. The date of Chinese New Year varies each year according to the lunar calendar, typically falling between January 21st and February 20th on the Gregorian calendar.The festival is celebrated with various customs, traditions, and activities, which may vary among different regions and communities. Some common elements of Chinese New Year celebrations include",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-17"),
        categoryId: 2,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://upload.wikimedia.org/wikipedia/en/5/5c/Ghosts.PeeTaKhon2.jpg",
        title: "Phi Ta Khon",
        description:
            "Phi Ta Khon (Thai: ผีตาโขน; phǐi taa khǒn; [pʰǐː taː kʰǒn]) is a festival held in Dan Sai, Loei province, Isan, Thailand. The events take place over three days sometime between March and July, the dates being selected annually by the town’s mediums.The whole event is called Bun Luang, part of a Buddhist merit-making holiday also known as Bun Phawet (assembly day). The town’s residents invite protection from Phra U-pakut, the spirit of the Mun river. They then hold a series of games and take part in a procession wearing masks made of the sheaths or bottom part of thick palm leaf stems.",
        startDate: new Date("2024-03-13"),
        endDate: new Date("2024-03-14"),
        categoryId: 2,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://mpics.mgronline.com/pics/Images/566000009624503.JPEG",
        title: "Phuket Vegeterian Festival",
        description:
            "The Phuket Vegetarian Festival is an annual event held in Phuket, Thailand. It usually takes place during the ninth lunar month of the Chinese calendar. The festival is celebrated by the Chinese community in Phuket, who observe a strict vegetarian diet for nine days as a form of purification and merit-making.During the festival, participants dress in white and refrain from consuming meat, poultry, seafood, and other animal products. They also avoid certain strong-smelling vegetables such as garlic and onions. Many devotees perform acts of self-mortification, including piercing their cheeks with various objects and participating in processions to honor the Nine Emperor Gods.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-13"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage: "https://s.isanook.com/ho/0/ud/3/15073/b-3.jpg",
        title: "Boon Bang Fai",
        description:
            "Boon Bang Fai, also known as the Rocket Festival, is an annual traditional festival celebrated in northeastern Thailand, particularly in the region of Isan. The festival usually takes place around May, marking the beginning of the rainy season and aiming to encourage rainfall for successful agricultural harvests.During the Boon Bang Fai festival, communities build large bamboo rockets, often decorated elaborately, and launch them into the sky. The rockets are believed to provoke the rain gods to bring much-needed rainfall to the region. The festival is accompanied by lively music, dancing, and parades, creating a festive atmosphere.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-11"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://cdn.i-scmp.com/sites/default/files/d8/images/canvas/2023/04/03/8cb12ab6-e927-4b3f-b754-cac99e33d64f_c6f7589c.jpg",
        title: "Songkran Festival",
        description:
            "The Songkran Festival is one of the most important and widely celebrated traditional festivals in Thailand. It marks the Thai New Year and usually falls on April 13th every year, although the celebration may extend for several days, depending on the region.The festival is known for its water-related activities, where people engage in friendly water fights and douse each other with water as a symbol of cleansing and purification for the new year. Water is also used to wash away bad luck and to bring good fortune for the upcoming year. During Songkran, streets across Thailand are transformed into lively water battlegrounds, with locals and tourists alike armed with water guns, hoses, and buckets.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-12"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 4,
        coverImage: "https://cms.dmpcdn.com/travel/2020/09/28/3dae42c0-0164-11eb-97e4-65e826b4aa8c_original.JPG",
        title: "Naga Fireball",
        description:
            "The fireballs are most often reported around the night of Wan Ok Phansa at the end of Buddhist Lent in late-October.[3] Naga fireballs have been reported over an approximately 250 km (160 mi) long section of the Mekong River centered approximately on Phon Phisai in the Phon Phisai District. Fireballs have also been reported rising from smaller rivers, lakes and ponds in the region. The fireballs were called 'ghost lights' by locals until the mid-1980s, when the local council officially named them phaya nak lights. In 2018 one observer noted that while the light phenomenon is 'hundreds of years old', the new name Phaya Nak lights is only about 35 years old.",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-16"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://cms.dmpcdn.com/travel/2021/07/20/601500a0-e940-11eb-812d-d3adbb9acce8_original.jpg",
        title: "Buddism Candle Festival",
        description:
            "The term Buddhism Candle Festival could refer to various festivals or events related to Buddhism that involve candles. One example is the Vesak Day or Buddha Day,which is celebrated by Buddhists around the world to commemorate the birth, enlightenment, and death of Gautama Buddha. During Vesak Day, candles are often lit as part of the celebrations to symbolize enlightenment and to honor the Buddha's teachings",
        startDate: new Date("2024-03-17"),
        endDate: new Date("2024-03-18"),
        categoryId: 1,
        timePeriod: "08:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://www.theakyra.com/files/5015/7043/7475/Bo_Sang_Umbrella_Festival.jpg",
        title: "Full moon PhaNgarn island",
        description:
            "Koh Phangan Full Moon Party has become a world-famous institution, but its ancestral home remains the crescent cove of Haad Rin Beach on the southernmost tip of Phangan Island in Thailand. More than 12 powerful sound systems turn the 800-metre beach into possibly the most popular open-air nightclub in the world once a month, with a lively festival-like atmosphere, great music and huge quantities of alcohol. This one-of-a-kind event is routinely listed on bucket lists as one of the essential experiences in Thailand which absolutely must be seen to be believed.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-13"),
        categoryId: 4,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 1,
        coverImage: "https://a.cdn-hotels.com/gdcs/production31/d653/09d20665-cfa3-4efd-a423-9b30dc2517d2.jpg?impolicy=fcrop&w=1600&h=1066&q=medium",
        title: "Bo Sang Umbrella Festival",
        description:
            "The Bo Sang Umbrella Festival is an annual event held in Bo Sang Village near Chiang Mai, Thailand. Celebrated for over a century, it showcases the traditional craft of umbrella making with vibrant displays of hand-painted umbrellas and parasols. Visitors can witness colorful parades, cultural performances, and participate in umbrella painting workshops. This festival highlights the rich cultural heritage of the region and attracts tourists from around the world.",
        startDate: new Date("2025-01-19"),
        endDate: new Date("2025-01-19"),
        categoryId: 4,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage: "https://f.ptcdn.info/530/032/000/1434550481-DSC032601j-o.jpg",
        title: "Ayuthaya Light up",
        description:
            "Ayutthaya: the former capital of Siam, Ayutthaya had palaces laden with gold, large monuments and elaborate Buddha's - all of this grandeur came to an end when the Burmese burnt the city to the ground, destroying all of its riches. Now all that remains are ruins of the historic events that took place there - the city is now on the list of UNESCO world heritage sites. Take a trip to this incomparable ancient city with local Bangkok tours, where you will get the best prices along with the best experiences",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-16"),
        categoryId: 6,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 3,
        coverImage: "https://i0.wp.com/www.tatnews.org/wp-content/uploads/2022/07/Sukhothai-Historical-Park-1.jpg?fit=1200%2C742&ssl=1",
        title: "Sukhothai Light up",
        description:
            "Sukhothai: the former capital of Siam, Ayutthaya had palaces laden with gold, large monuments and elaborate Buddha's - all of this grandeur came to an end when the Burmese burnt the city to the ground, destroying all of its riches. Now all that remains are ruins of the historic events that took place there - the city is now on the list of UNESCO world heritage sites. Take a trip to this incomparable ancient city with local Bangkok tours, where you will get the best prices along with the best experiences",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-17"),
        categoryId: 6,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://pbs.twimg.com/media/GHM43aqaoAASopM?format=jpg&name=900x900",
        title: "Khao Wong Prajan Light up",
        description:
            "Khao Wong Prajarn is a Thai term that translates to Moon Crescent Hill in English. This is a famous historical site located in Ratchaburi Province, Thailand. It is also known as Khao Phra Chan or Khao Chan Daeng.Khao Wong Prajarn is renowned for its unique natural rock formations, which resemble a crescent moon when viewed from a distance. These formations are believed to have been naturally shaped over millions of years by erosion and weathering processes.",
        startDate: new Date("2024-03-18"),
        endDate: new Date("2024-03-19"),
        categoryId: 2,
        timePeriod: "20:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 5,
        coverImage: "https://media.komchadluek.net/media/img/size1/2017/06/30/zogb5hih55kideefeaabki7a.jpg?x-image-process=style/LG-webp",
        title: "Buffalo racing",
        description:
            "The Buffalo Racing Festival or Wing Kwai is one of the most exciting events of the calendar in Chonburi province. The annual race is held in celebration of the water buffalo as an icon of Thailand’s agrarian way of life, giving locals a chance to get together, compete in thrilling competitions, and enjoy delicious, local cuisine.Dating back to 150 years ago, the event is perfect for anyone looking for a unique Thai experience that cannot be found elsewhere.",
        startDate: new Date("2024-03-14"),
        endDate: new Date("2024-03-17"),
        categoryId: 3,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://s.isanook.com/tr/0/ud/278/1391125/2.jpg",
        title: "Long Boat racing",
        description:
            "The season of long boat races is finally here. Long boat-racing has always been one of Thailand’s signature sport festivals, held annually during Thai Buddhist Lent period which is around September and October since the river’s tide is highest. The purpose is to display the bond between local Thais and the river and to show moral, courage, and strength of the rowing crew. It has been being held since the old Thai era (approx. 600 year ago.)",
        startDate: new Date("2024-03-18"),
        endDate: new Date("2024-03-20"),
        categoryId: 3,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage:
            "https://scontent.fbkk7-3.fna.fbcdn.net/v/t31.18172-8/18238565_1683026615048444_7055562275172768252_o.jpg?_nc_cat=108&ccb=1-7&_nc_sid=5f2048&_nc_ohc=mYgcPbmMyhoAX_qBHLv&_nc_oc=AQk47M-mASY1KGX_UNOfQSEe6-77Z_501_uh2Ku9PSp9Yd729PJhr0BtljqY7KkSi-Y&_nc_ht=scontent.fbkk7-3.fna&oh=00_AfCwUIdF1hRDheKCE6cleedvySo9m1dEGDObkAKjNbWNPg&oe=660FBADA",
        title: "Water Thai Boxing",
        description:
            "When it comes to sports in Thailand, the first thing that comes to mind is Muay Thai. But do you know about the origins of Thailand’s National Sport? Team Thailand Insider is here to share with you the history, important Muay Thai figures, and where to watch the jaw-clenching sport in Thailand.As Thailand’s national sport, Muay Thai, or Thai Boxing, is the most popular sport in the country. As a martial art originating from the Siamese army, people travel from all over the globe to learn this historically rooted sport. Muay Thai is referred to as “The Art of Eight Limbs” due to the eight points of contact the body uses, mimicking weapons of war.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-15"),
        categoryId: 3,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage:
            "https://ryuisnow.com/wp-content/uploads/2023/03/%E0%B8%9E%E0%B8%B8%E0%B9%88%E0%B8%87%E0%B9%83%E0%B8%95%E0%B9%89%E0%B9%80%E0%B8%9F%E0%B8%AA-4-1024x683.jpg",
        title: "Chang Music Connection",
        description:
            "The Chang Music Festival is a popular music festival held in Thailand. It is organized by Chang Beer, a well-known Thai beer brand. The festival typically features a diverse lineup of local and international artists across various music genres, including pop, rock, electronic dance music (EDM), hip-hop, and more.The Chang Music Festival is known for its vibrant atmosphere, with attendees enjoying live music performances, food and drinks, and other entertainment activities. The festival often attracts large crowds and has become a significant event in Thailand's music scene.",
        startDate: new Date("2024-03-08"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 3,
        coverImage: "https://image.springnews.co.th/uploads/images/md/2024/02/ZUU5By9qNOMpIjZg4bXC.webp?x-image-process=style/LG-webp",
        title: "Pattaya Music Pattaya",
        description:
            "The Pattaya Music Festival is an annual event held in the beach city of Pattaya, Thailand. It typically takes place over a weekend and features a wide range of musical performances across various genres, including pop, rock, jazz, electronic dance music (EDM), and traditional Thai music.The festival attracts both local and international artists, showcasing talent from Thailand and beyond. It often spans multiple stages set up along the beach, allowing attendees to enjoy different acts while taking in the scenic views of the coastline.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "19:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://mpics.mgronline.com/pics/Images/557000003809501.JPEG",
        title: "Tractor racing",
        description:
            "Tractor racing is a unique motorsport where modified tractors compete against each other in races. These races typically take place on dirt tracks or fields, and the tractors are specially designed and modified for racing purposes.In tractor racing, competitors often modify their tractors to enhance performance, including upgrading the engine, improving traction, and optimizing weight distribution. Some modifications may also involve adding safety features such as roll cages and seat belts to protect the drivers.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 5,
        coverImage:
            "https://d12eu00glpdtk2.cloudfront.net/public/images/news/visit-qatar-kite-festival-returns-second-edition-25-january-2024/_910x600_clip_center-center_none/visit-qatar-kite-festival-returns-second-edition-25-january-2024-cover-image.jpeg",
        title: "Cha-Am Kite Festival",
        description:
            "The Cha-Am International Kite Festival is a vibrant annual event held in Cha-Am, a beach resort town in Thailand. The festival typically takes place in March and attracts kite enthusiasts from around the world.During the Cha-Am Kite Festival, the skies above the beach are filled with colorful kites of various shapes and sizes. Participants showcase their creativity and skills by flying kites of traditional designs as well as more elaborate and innovative creations",
        startDate: new Date("2024-03-14"),
        endDate: new Date("2024-03-15"),
        categoryId: 5,
        timePeriod: "15:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://images.ahotu.com/9zsf3d2n86q3ldrn4x6rua4g0mpq?w=1920&f=webp",
        title: "Huahin Marathon",
        description:
            "The Hua Hin Marathon is an annual running event held in Hua Hin, Thailand. Hua Hin is a popular beach resort town located on the Gulf of Thailand, known for its beautiful beaches and vibrant atmosphere. The marathon typically takes place in either late spring or early winter, depending on the specific year.The Hua Hin Marathon offers various race distances to cater to runners of different levels and preferences. These may include a full marathon (42.195 kilometers), a half marathon (21.1 kilometers), a 10-kilometer race, and sometimes shorter distances for children or fun runs.",
        startDate: new Date("2024-03-20"),
        endDate: new Date("2024-03-22"),
        categoryId: 3,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 1,
        coverImage: "https://images.ahotu.com/6brr1pa3mw5wu4sjzjbajj9l62mk?w=1920&f=webp",
        title: "Bangsaen Marathon",
        description:
            "Come join us for the prestigious BANGSAEN42 CHONBURI MARATHON! Ranked number one for two consecutive years as the Best Full Marathon Event (by WingNaiDee) and winner of the Runners’ Choice 2018 Award, this full marathon race consists of 42.195 km and is the only MICE & Communication Marathon of the year.",
        startDate: new Date("2024-03-19"),
        endDate: new Date("2024-03-20"),
        categoryId: 3,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 2,
        coverImage: "https://images.ahotu.com/31wp709d97v6gyja2lkikf9mvafy?w=1920&f=webp",
        title: "Amazing Thailand Marathon",
        description:
            "Experience the renowned hospitality of Thailand and join world-class athletes on an incredible running route in Bangkok. Run through must-see sights such as the Victory Monument, King Rama V Monument, and Rama VIII Bridge, beginning at the Rajamangala National Stadium and ending at the Democracy Monument. With four categories to choose from – Marathon, Half Marathon, 10km, and 5km Family Fun Run – there's something for everyone, no matter your running experience. Come join us and have some fun!",
        startDate: new Date("2024-03-22"),
        endDate: new Date("2024-03-24"),
        categoryId: 3,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    // ====================================== new Data ================================================== //

    {
        organizerInformationId: 3,
        coverImage: "https://www.chiangmai-alacarte.com/wp-content/uploads/2021/06/Poy-Sang-Long-stage-1024x576.jpg",
        title: "Poy Sang Long Festival",
        description:
            "The Poy Sang Long Festival is a traditional rite of passage for young boys of the Shan ethnic group in Northern Thailand. During the ceremony, young boys are ordained as novice monks and participate in colorful processions, dances, and rituals. The festival is a vibrant celebration of culture and spirituality, drawing visitors from across the region.",
        startDate: new Date("2024-04-10"),
        endDate: new Date("2024-04-12"),
        categoryId: 1,
        timePeriod: "06:00-16:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://itsbetterinthailand.com/wp-content/uploads/2018/03/P1055576.jpg",
        title: "Surin Elephant Round-up",
        description:
            "The Surin Elephant Round-up is a unique and thrilling event showcasing the majestic elephants of Surin Province. Visitors can witness impressive elephant shows, including demonstrations of traditional forestry skills, mock battles, and ceremonial processions. The event also features cultural performances, handicraft markets, and opportunities to learn about elephant conservation efforts.",
        startDate: new Date("2024-11-15"),
        endDate: new Date("2024-11-15"),
        categoryId: 1,
        timePeriod: "09:00-17:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://www.khaolaklanddiscovery.com/wp-content/uploads/2024/03/Releasing-Turtles-Back-to-the-Wild.jpg",
        title: "Turtle Conservation Festival in Khao Lak",
        description:
            "The Pattaya Music Festival is an annual event held in the beach city of Pattaya, Thailand. It typically takes place over a weekend and features a wide range of musical performances across various genres, including pop, rock, jazz, electronic dance music (EDM), and traditional Thai music.The festival attracts both local and international artists, showcasing talent from Thailand and beyond. It often spans multiple stages set up along the beach, allowing attendees to enjoy different acts while taking in the scenic views of the coastline.",
        startDate: new Date("2024-04-22"),
        endDate: new Date("2024-04-22"),
        categoryId: 2,
        timePeriod: "09:00-12:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage:
            "https://scontent.fbkk22-8.fna.fbcdn.net/v/t31.18172-8/24958722_1117770284926105_8056797883881037328_o.jpg?_nc_cat=108&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHNz3GYg8TBlGBv2lYY9R56A7E7KzENGpoDsTsrMQ0amker7VToeHtus9utcY1sG6M&_nc_ohc=t2ipYVNWGMIAX8B1WP6&_nc_ht=scontent.fbkk22-8.fna&oh=00_AfDOiSnp8QdGFmNv3gDfx974osWrPUG98FLJtFTJrPBDBQ&oe=66103490",
        title: "Phuket King's Cup Regatta",
        description:
            "The Phuket King's Cup Regatta is one of the most prestigious sailing events in Asia, held annually in the waters off the coast of Phuket. Established in 1987 to celebrate the King of Thailand's birthday, the regatta attracts sailors from around the world to compete in a series of challenging yacht races. Participants compete in various classes, from small dinghies to large ocean-going yachts, making it a diverse and exciting event. Beyond the races, the regatta offers social events, parties, and festivities both onshore and offshore, providing participants and spectators alike with an unforgettable experience.",
        startDate: new Date("2024-11-30"),
        endDate: new Date("2024-12-07"),
        categoryId: 3,
        timePeriod: "10:00-15:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://www.thailandnow.in.th/wp-content/uploads/2021/10/Illuminated-Boat-Procession.jpg.webp",
        title: "Nakhon Phanom Illuminated Boat Procession",
        description:
            "The Nakhon Phanom Illuminated Boat Procession features beautifully decorated boats floating along the Mekong River, illuminated with colorful lights. This traditional event celebrates the end of Buddhist Lent.",
        startDate: new Date("2024-10-20"),
        endDate: new Date("2024-10-30"),
        categoryId: 1,
        timePeriod: "18:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://www.ferrysamui.com/upload/images/2210/635792aa1d76f.jpg",
        title: "Chumphon Marine Festival",
        description:
            "The Chumphon Marine Festival celebrates the coastal culture and marine biodiversity of Chumphon Province. Visitors can enjoy boat races, snorkeling trips, seafood feasts, and cultural performances.",
        startDate: new Date("2024-03-22"),
        endDate: new Date("2024-03-26"),
        categoryId: 3,
        timePeriod: "08:00-17:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://images.ahotu.com/31wp709d97v6gyja2lkikf9mvafy?w=1920&f=webp",
        title: "Ubon Ratchathani Candle Festival",
        description:
            "The Ubon Ratchathani Candle Festival, also known as Ubon Ratchathani Candle Procession and Wax Castle Festival, is an annual event held in Ubon Ratchathani Province to mark the beginning of Buddhist Lent, or Khao Phansa. The festival is renowned for its spectacular candle processions and elaborate wax sculptures, or Wax Castles, which are created by local temples and communities. These intricate and artistic displays depict scenes from Buddhist mythology, local legends, and cultural motifs. The candle processions, accompanied by traditional music and dance performances, traverse through the streets of Ubon Ratchathani, captivating spectators with their beauty and symbolism. The festival also includes religious ceremonies, merit-making activities, and food stalls offering local delicacies.",
        startDate: new Date("2024-07-19"),
        endDate: new Date("2024-07-21"),
        categoryId: 3,
        timePeriod: "10:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://www.phuketbikeweek.com/wp-content/uploads/2022/11/PBW_12-Mar-2018-119.jpg",
        title: "Phuket Bike Week 2024",
        description:
            "Phuket Bike Week brings together motorcycle enthusiasts from around the world for a series of rides, exhibitions, and live music concerts. Participants can join scenic bike tours across the island, attend custom bike shows, and socialize at biker-friendly venues.",
        startDate: new Date("2024-04-13"),
        endDate: new Date("2024-04-20"),
        categoryId: 2,
        timePeriod: "09:00-24:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage: "https://lifestyleinthailand.com/wp-content/uploads/2023/03/Fashion_C1-409-scaled.jpg",
        title: "Phuket Fashion Week 2024",
        description:
            "Phuket Fashion Week 2024 is a fashion show, currently in its second year, featuring the creations of both Thai and international fashion designers. It serves as a platform for emerging and established designers to showcase their collections to an audience comprising fashion industry professionals, buyers, and the media.",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-16"),
        categoryId: 4,
        timePeriod: "17:00-22:00",
        isYearly: true,
        isPublish: false,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://www.ttrweekly.com/site/wp-content/uploads/2022/05/Supersports-Laguna-Phuket-Marathon-4_m.jpg",
        title: "Laguna Phuket Marathon",
        description:
            "The Laguna Phuket Marathon is a certified international marathon that attracts runners from all over the world. The course winds its way through stunning scenery, including local villages, coconut plantations, and Sirinat National Park.",
        startDate: new Date("2024-06-08"),
        endDate: new Date("2024-06-09"),
        categoryId: 3,
        timePeriod: "19:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://www.thephuketnews.com/photo/listing/1398222790_1-org.jpg",
        title: "Phuket Pride Festival",
        description:
            "Phuket Pride is an annual LGBTQ celebration on the island of Phuket, Thailand. It's known for its vibrant parties, cultural shows, a colorful pride parade, and more. Organized by local LGBTQ groups and businesses, the festival promotes awareness, equality, and inclusivity.  The main events are centered around Patong Beach, a hub for Phuket's LGBTQ scene. Festivities include drag queen performances, boat parties, cultural exhibits, and a culmination with the dynamic pride parade. Proceeds from the event often go to LGBTQ and HIV charities.",
        startDate: new Date("2024-06-04"),
        endDate: new Date("2024-06-30"),
        categoryId: 2,
        timePeriod: "10:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://pbs.twimg.com/media/C6jGErgV0AAI8hG?format=jpg&name=medium",
        title: "12th International Kite Festival in Cha Am 2024",
        description:
            "This International Kite Festival held in Cha-Am, Phetchaburi province showcases a stunning display of kites from all over the world. Visitors can expect to see giant character kites, stunt kites, and unique regional kites. There are also kite-flying demonstrations, competitions, workshops, and food stalls.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-11"),
        categoryId: 2,
        timePeriod: "09:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://www.agoda.com/wp-content/uploads/2024/02/2-Prasat-Phanom-Rung-Buriram-Temples-in-Northeast-Thailand.jpg",
        title: "Phanom Rung Light Phenomenon",
        description:
            "The Phanom Rung Light Phenomenon is a unique spectacle where the rising sun aligns perfectly with the 15 doorways of the temple's sanctuary, casting an ethereal light through the corridors. This alignment creates a breathtaking visual effect, illuminating the ancient stone structures and highlighting the intricate carvings and bas-reliefs of Phanom Rung temple. The phenomenon symbolizes the harmony between nature and architecture, showcasing the advanced astronomical knowledge of the Khmer civilization that built the temple between the 10th and 13th centuries.",
        startDate: new Date("2024-03-05"),
        endDate: new Date("2024-03-07"),
        categoryId: 6,
        timePeriod: "17:00-19:00",
        isYearly: true,
        isPublish: true,
        isExpired: true,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://img.kapook.com/u/sutasinee/15/6.02.56/DSC_0021e1.jpg",
        title: "Lamduan Flower Festival",
        description:
            "The Lamduan Flower Festival is a vibrant celebration that showcases the rich diversity of Thai culture through the customs, arts, cuisine, and performances of the four main ethnic groups in Thailand. Each group contributes to the festival with unique traditions, clothing, music, dance, and culinary specialties, creating a colorful tapestry of cultural experiences for visitors to enjoy. The festival often features traditional ceremonies, parades, cultural exhibitions, folk music and dance performances, as well as food stalls offering a wide array of authentic dishes from each ethnic group. The Lamduan flower, known for its delicate beauty and sweet fragrance, serves as a central motif of the festival, adorning the event venues and adding to the festive atmosphere.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-13"),
        categoryId: 4,
        timePeriod: "18:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage: "https://what-to-do-in.co.uk/wp-content/uploads/LOT-night.jpeg",
        title: "Laanta Lanta Festival",
        description:
            "The Laanta Lanta Festival celebrates the unique culture, traditions, and heritage of Koh Lanta, an island known for its pristine beaches, diverse marine life, and laid-back atmosphere. During the festival, visitors can immerse themselves in the island's rich cultural heritage through a variety of activities, including traditional Thai dance performances, live music concerts, Muay Thai boxing matches, and local food and craft markets. There are also cultural exhibitions showcasing the history and customs of the local sea gypsy communities, as well as opportunities to participate in hands-on workshops such as batik painting, fruit carving, and traditional cooking classes. The festival aims to promote sustainable tourism and preserve the cultural identity of Koh Lanta while providing an unforgettable experience for both locals and visitors alike.",
        startDate: new Date("2024-03-07"),
        endDate: new Date("2024-03-09"),
        categoryId: 1,
        timePeriod: "16:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 7,
        coverImage: "https://mpics-cdn.mgronline.com/pics/Images/565000001432601.JPEG",
        title: "Amazing Robusta@Chumphon 2024",
        description:
            "Calling all coffee lovers! This 3-day festival is your chance to delve into the world of Chumphon's prized Robusta coffee. Explore a wide variety of coffee shops showcasing their unique brews and brewing methods.  In addition to coffee, the event features delicious local food, traditional products, and exciting stage performances with live music.",
        startDate: new Date("2024-03-08"),
        endDate: new Date("2024-03-10"),
        categoryId: 2,
        timePeriod: "11:00-21:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage:
            "https://cdn1.citylife.group/tat1/wp-content/uploads/2020/07/%E0%B8%94%E0%B8%AD%E0%B8%81%E0%B9%80%E0%B8%AA%E0%B8%B5%E0%B9%89%E0%B8%A2%E0%B8%A7%E0%B8%9A%E0%B8%B2%E0%B8%99_200128_0001-1140x760.jpg",
        title: "Ban Pa Muang Orchid Tree Blossoms Festival",
        description:
            "This festival showcases the stunning sight of the Pink Orchid Trees (Bauhinia Rufescens) in full bloom, transforming the landscape into a sea of pink. Visitors can enjoy the picturesque scenery, participate in cultural activities, and indulge in local delicacies.",
        startDate: new Date("2024-03-08"),
        endDate: new Date("2024-03-12"),
        categoryId: 2,
        timePeriod: "09:00-17:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://www.shutter.run/img/2024011614381183.jpg",
        title: "Pangsida Chill 2024 Run & Have Fun Season 2",
        description:
            "This is a Cross Country Course run, meaning it takes place on natural terrain through Pang Sida National Park. Enjoy the scenery and challenge yourself amidst the mountains! Part of the race proceeds go towards supporting the park's operations and forest conservation.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-10"),
        categoryId: 3,
        timePeriod: "05:30-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 1,
        coverImage: "https://4.bp.blogspot.com/-amI_rpPa9CE/VjHd9xiwGtI/AAAAAAAAAHE/XxbYoNorWiw/s1600/663506d63%2B%25281%2529.jpg",
        title: "34th Roi Et Bun Phawet 2024",
        description:
            "This three-day festival celebrates life and the teachings of Buddha. It's a time for locals to make merit for good luck and well-being of themselves and their ancestors.",
        startDate: new Date("2024-03-15"),
        endDate: new Date("2024-03-17"),
        categoryId: 1,
        timePeriod: "07:00-15:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage:
            "https://sports-images.vice.com/images/articles/meta/2017/03/24/wai-kru-festival-ayutthaya-the-comic-con-of-muay-thai-1490374239.jpg",
        title: "World Wai Kru Muay Thai Ceremony 2024",
        description:
            "This grand ceremony is a beautiful display of respect and gratitude. Muay Thai fighters from all over the world gather to perform the Wai Kru ritual, a series of dance-like movements accompanied by traditional Thai music.",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-17"),
        categoryId: 1,
        timePeriod: "17:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://www.thailand.go.th/uploads/posts/w1200.jpg",
        title: "Hok Peng Festival 2024",
        description:
            "This annual festival celebrates the full moon of the sixth Northern Thai lunar month (Hok Peng).  The centerpiece is worshipping the sacred relics enshrined at Wat Phra That Chae Haeng, considered the most sacred temple in Nan province.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-12"),
        categoryId: 4,
        timePeriod: "19:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://thailandeventguide.com/wp-content/uploads/2024/03/Phukets-best-burger-1.jpg",
        title: "Phuket’s best burger",
        description:
            "Phuket is known as the jewel of Thailand’s Andaman Sea. It’s renowned for its pristine beaches, vibrant culture, and delectable cuisine. Amidst this tropical paradise, this annual Phuket’s Best Burger 8 event is scheduled to take place at the picturesque Blue Tree Lagoon Phuket on March 23, 2024.",
        startDate: new Date("2024-03-23"),
        endDate: new Date("2024-03-23"),
        categoryId: 2,
        timePeriod: "17:00-20:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 7,
        coverImage: "https://www.wmomuaythai.org/wp-content/uploads/2024/01/1000030267-1024x576.jpg",
        title: "Phuket International & Thai Martial Arts Games (ITMA Games)",
        description:
            "This annual event is a celebration of Thai culture and martial arts. It features competitions in various martial arts disciplines like Muay Thai, Muay Boran, Kickboxing, and more. Enthusiasts of all ages from around the world participate and showcase their skills.",
        startDate: new Date("2024-03-10"),
        endDate: new Date("2024-03-17"),
        categoryId: 3,
        timePeriod: "17:00-23:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://www.thailand.go.th/uploads/posts/photo_1678820136_0.jpeg",
        title: "Worship and Bathing Ceremony of Phra That Doi Tung",
        description:
            "The Worship and Bathing Ceremony is a revered tradition observed by Buddhists to pay homage to the Phra That Doi Tung, a sacred relic believed to contain relics of the Buddha. The ceremony begins with Buddhist devotees gathering at the temple to participate in religious rituals, prayers, and merit-making activities. One of the highlights of the ceremony is the ritualistic bathing of the Phra That Doi Tung, where worshippers use scented water and flower petals to cleanse and purify the sacred relic. This symbolic act is performed as an expression of reverence and devotion to the Buddha and is believed to bring blessings and spiritual merit to those who participate. Throughout the ceremony, monks chant prayers and deliver sermons on Buddhist teachings, while worshippers offer alms, flowers, and incense as acts of devotion.",
        startDate: new Date("2024-03-24"),
        endDate: new Date("2024-03-24"),
        categoryId: 6,
        timePeriod: "08:00-12:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://thailandeventguide.com/wp-content/uploads/2024/03/Trat-City-Night-Fun-Run-2024-1.jpg",
        title: "Trat City Night & Fun Run 2024",
        description:
            "The 9 km route winds through Trat City, showcasing both its modern and historical charm. You might pass by hidden art installations, like murals or sculptures, specifically created for the event.  Keep an eye out for Hidden Art signs along the way!   The course also includes iconic landmarks like Wat Buppharam, a beautiful Buddhist temple,  and the Trat walking street, known for its local shops and food stalls.",
        startDate: new Date("2024-03-09"),
        endDate: new Date("2024-03-12"),
        categoryId: 3,
        timePeriod: "13:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://i.ibb.co/ynxjQp5/421243391-1102449251094869-4542345777245830725-n.jpg",
        title: "MCOT Bike Low Carbon @Koh Jum",
        description:
            "Eco-Friendly Vibe: Given the Low Carbon aspect of the name, expect an emphasis on sustainability. Participants might be environmentally conscious cyclists who enjoy exploring nature responsibly. Organizers might use reusable water bottles and promote eco-friendly practices throughout the event.",
        startDate: new Date("2024-03-31"),
        endDate: new Date("2024-03-31"),
        categoryId: 3,
        timePeriod: "06:30-12:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://a.cdn-hotels.com/gdcs/production29/d995/b7accadc-8612-42eb-9a36-cf4e233cfdf7.jpg",
        title: "Thao Thepkasattri-Thao Sri Suntorn Festival",
        description:
            "The Thao Thepkasattri-Thao Sri Suntorn Festival celebrates the courage and legacy of Thao Thepkasattri and Thao Sri Suntorn, who, according to legend, led the local residents in defending Phuket against Burmese invaders during the Burmese–Siamese War of 1785. The festival features a range of cultural and historical activities",
        startDate: new Date("2024-03-13"),
        endDate: new Date("2024-03-15"),
        categoryId: 6,
        timePeriod: "17:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 1,
        coverImage: "https://framerusercontent.com/images/Ygr5QgHZJ7Yddw2Bkkvem1cE.jpg",
        title: "The Glory of Siam Night Museum",
        description:
            "Step in the antique world of imagination, incredible illuminations, light-ups, musics & arts inspired by the King Rama VI's royal poetry; The Romance of A Rose (MADANABADHA). During the event, millions of LED lights will be wrapped around giant trees and buildings, creating a stunning visual display along with 3D Light projection show, turning the palace into a sparkling wonderland. Take a break and enjoy a lot of Thai street foods or savor a taste of authentic Thai recipe at Cafe Narasighn, the heritage cafe located in the palace during the visit.",
        startDate: new Date("2024-03-14"),
        endDate: new Date("2024-03-16"),
        categoryId: 5,
        timePeriod: "18:00-21:30",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://i.ibb.co/sK5v8hk/Samui-Island-Regatta.jpg",
        title: "Koh Samui Regatta",
        description:
            "The Koh Samui Regatta is an annual sailing event held off the coast of Koh Samui, one of Thailand's most popular tourist destinations. It features competitive yacht racing in the beautiful waters surrounding the island. Participants compete in various classes, from small dinghies to large keelboats, in a series of races testing their sailing skills and strategy. The regatta attracts a diverse fleet of boats and sailors, ranging from amateur enthusiasts to seasoned professionals, creating a dynamic and exciting atmosphere both on and off the water. In addition to the races, the regatta also includes social events, parties, and award ceremonies, providing opportunities for participants and spectators to mingle, celebrate, and enjoy the vibrant island lifestyle of Koh Samui.",
        startDate: new Date("2024-05-25"),
        endDate: new Date("2024-06-01"),
        categoryId: 3,
        timePeriod: "10:00-19:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://photos.smugmug.com/Thailand/Events-Festivals/i-9BTVqbx/0/90a1ebc1/XL/Chiang%20Mai-59-XL.jpg",
        title: "Inthakin Festival",
        description:
            "The Inthakin Festival is a traditional Lanna (northern Thai) ceremony dedicated to the City Pillar, known as Sao Inthakin or Lak Mueang, which is believed to protect the city and its inhabitants. The festival dates back centuries and is deeply rooted in Buddhist and animist beliefs. During the festival, elaborate rituals and ceremonies are conducted at Wat Chedi Luang, one of Chiang Mai's most revered temples, which houses the City Pillar. These rituals include merit-making activities such as offering alms to monks, making floral offerings (known as Khan Dok), and circumambulating the temple's main pagoda.",
        startDate: new Date("2024-05-14"),
        endDate: new Date("2024-05-24"),
        categoryId: 1,
        timePeriod: "06:00-10:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://thaiwave.club/wp-content/uploads/2021/11/6.jpg",
        title: "35th Lopburi Monkey Buffet Festival",
        description:
            "The Lopburi Monkey Buffet Festival is a celebration that pays homage to the resident macaque monkeys of Lopburi, who are considered sacred and are an integral part of the city's culture and identity. During the festival, local residents and visitors gather to offer a lavish buffet spread to the monkeys, consisting of various fruits, vegetables, and other treats. The buffet is set up in the heart of the city, near the ancient ruins of Phra Prang Sam Yot temple, which is home to a large population of macaques.",
        startDate: new Date("2024-11-26"),
        endDate: new Date("2024-11-26"),
        categoryId: 2,
        timePeriod: "11:00-15:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 5,
        coverImage: "https://tatapi.tourismthailand.org/tatfs/IMAGE/Event/Picture/E0002013.jpg",
        title: "Phra Nakhon Khiri Festival",
        description:
            "The Pattaya Music Festival is an annual event held in the beach city of Pattaya, Thailand. It typically takes place over a weekend and features a wide range of musical performances across various genres, including pop, rock, jazz, electronic dance music (EDM), and traditional Thai music.The festival attracts both local and international artists, showcasing talent from Thailand and beyond. It often spans multiple stages set up along the beach, allowing attendees to enjoy different acts while taking in the scenic views of the coastline.",
        startDate: new Date("2024-03-16"),
        endDate: new Date("2024-03-24"),
        categoryId: 1,
        timePeriod: "17:00-22:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 6,
        coverImage: "https://media.megatix.com.au/e/32183/NvftsNVfNvS5Oh07UW7gmqnHAyGc3c1CthPeU7cT.jpg",
        title: "Techno Yacht Party, Pattaya, by Rave Times",
        description:
            "We are back on the Sea! Kicking of the yacht party season on the biggest party yacht in pattaya  dance with over 80 people into the sunset",
        startDate: new Date("2024-04-06"),
        endDate: new Date("2024-04-06"),
        categoryId: 4,
        timePeriod: "13:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 1,
        coverImage: "https://media.megatix.com.au/e/32108/mY63Qfaps0b9la02LCRYhCk4sZThjsqNReZoY9zp.png",
        title: "Jungle Experience Festival ",
        description:
            "Embark on a sensational journey through sound and spectacle on April 22nd, 2024, as the Jungle Experience Festival transforms the tropical backdrop into an electrifying party playground. As the sun sets, the rhythms rise—welcoming night wanderers into a vibrant world of music, art, and entertainment.",
        startDate: new Date("2024-04-22"),
        endDate: new Date("2024-04-22"),
        categoryId: 4,
        timePeriod: "22:00-02:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://thethaiger.com/th/wp-content/uploads/2024/03/rollingloud.jpg",
        title: "Rolling Loud Thailand 2024",
        description:
            "Rolling Loud Thailand is part of the highly anticipated global Rolling Loud festival franchise, known for bringing the biggest names in hip-hop to stages worldwide. The Thailand edition promises an electrifying experience",
        startDate: new Date("2024-11-22"),
        endDate: new Date("2024-11-24"),
        categoryId: 4,
        timePeriod: "18:00-02:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 3,
        coverImage: "https://i.ibb.co/8KgHJyp/409591367-122113979066110579-6602387619256476846-n.jpg",
        title: "International Sand Sculpture Festival 2024",
        description:
            "The Phuket Sand Sculpture Festival is an annual artistic extravaganza where skilled sculptors from around the world gather to create stunning masterpieces entirely out of sand. Held on the pristine beaches of Phuket, this captivating event showcases intricate sculptures depicting a wide range of themes, from mythical creatures to cultural landmarks. Visitors are mesmerized by the creativity and detail exhibited in these ephemeral artworks, which are delicately crafted using only sand and water. The festival offers a unique opportunity to appreciate the beauty of sand artistry while enjoying the scenic backdrop of Phuket's shores. Alongside admiring the sculptures, attendees can participate in interactive workshops, watch live demonstrations, and even try their hand at sculpting. The Phuket Sand Sculpture Festival is a celebration of creativity, imagination, and the natural beauty of Thailand's coastline, making it a must-see attraction for art enthusiasts and beachgoers alike.",
        startDate: new Date("2024-04-30"),
        endDate: new Date("2024-05-19"),
        categoryId: 5,
        timePeriod: "10:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://i.ibb.co/8YLF5LK/358096016-255722013884387-3186064310468816661-n.jpg",
        title: "Blue Chevaliers Chess Tournament ",
        description:
            "The Blue Chevaliers Chess Tournament is a prestigious annual event, attracting skilled chess players from around the world. Held in a vibrant setting, this tournament offers an exhilarating atmosphere where strategic minds clash in intense battles of intellect. With players competing across various categories and skill levels, the tournament fosters a spirit of camaraderie and healthy competition. Participants engage in thrilling matches, showcasing their mastery of the game and vying for coveted titles and prizes. Whether a seasoned grandmaster or an aspiring enthusiast, the Blue Chevaliers Chess Tournament provides an unparalleled platform to challenge oneself, forge lasting connections, and celebrate the timeless allure of chess.",
        startDate: new Date("2024-07-21"),
        endDate: new Date("2024-07-27"),
        categoryId: 3,
        timePeriod: "09:00-17:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },

    {
        organizerInformationId: 6,
        coverImage: "https://epkkw.com/wp-content/uploads/2023/11/405130485_862156635912251_6836537249421546965_n.jpg",
        title: "Silk and Phuk Seow Festival 2024",
        description:
            "This festival  is an occasion held in Khon Kaen, Isan, Thailand more than ten days toward the finish of November and the start of December every year. It was first held in 1980. The occasion is fixated on advancement of the nearby silk industry, however incorporates an extensive of different exercises including parades and exhibitions of mor lam music. Thailand celebrations Silk and Phuk Seow. Thailand has for a considerable length of time been well known for its generation of silk and the making of silk pieces of clothing and no more so than the Northeastern city of Khon Kaen, which again plays host to this yearly silk-phuk-siew-celebration event.",
        startDate: new Date("2024-11-29"),
        endDate: new Date("2024-12-10"),
        categoryId: 4,
        timePeriod: "10:00-18:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 2,
        coverImage: "https://www.sunshine-workshops.com/images/public/sd_65d0511156f00.jpg?no_cache=1708154676",
        title: "Thai Massage & Osteopathy ",
        description:
            "This 5-day program is designed for intermediate and advanced practitioners, with previous experience in Thai Massage, who are looking to expand their horizons and search for new inspiration. Step by step, students will be guided to improve their ability to listen, palpate, feel and treat throughout the whole body.",
        startDate: new Date("2024-03-11"),
        endDate: new Date("2024-03-15"),
        categoryId: 2,
        timePeriod: "10:00-16:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
    {
        organizerInformationId: 4,
        coverImage: "https://i.ibb.co/dpySMW4/431777944-816978543809901-9191626877405963332-n.jpg",
        title: "Give the Gift of Life: Chiang Mai Blood Donation",
        description: "Your donation can save up to three lives. Be a hero, donate blood today.",
        startDate: new Date("2024-03-19"),
        endDate: new Date("2024-03-19"),
        categoryId: 2,
        timePeriod: "09:00-12:00",
        isYearly: true,
        isPublish: true,
        isExpired: false,
    },
]
